# -*- coding: utf-8 -*-
"""ML SUBLIME.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lpkP8Fvu5j2lbW1OAO8EcU8FkeOg5LXm

INTRODUZIONE (spiegazione dei file che abbiamo usato/consultato)

Installiamo la libreria per caricare automaticamente i datasets (train, validation e test sets) e visualizziamo le prime righe del training set:
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

!pip install datasets --quiet
from datasets import load_dataset

dataset = load_dataset("snli")
dataset["train"].to_pandas().head()

df_train =  dataset["train"].to_pandas()
df_validation = dataset["validation"].to_pandas()
df_test = dataset["test"].to_pandas()

df_train.head()

"""Mappiamo le etichette di classificazione da numeri a stringhe, creando una nuova colonna "label_text" con la versione testuale:"""

label_map = {
    0: "entailment",
    1: "neutral",
    2: "contradiction"
}

df_train["label_text"] = df_train["label"].map(label_map)
df_train[["premise", "hypothesis", "label", "label_text"]].head()

"""Prima del preprocessing controlliamo se ci sono valori nulli in ciascuna colonna:"""

df_train.isnull().sum()

"""Riscontriamo '785' valori mancanti nella colonna 'label text'

PREPROCESSING E CLEANING DATA:
"""

df_train["label"].unique()

"""Nel range è presente la label '-1' che risulta anomala, quindi teniamo solo le righe con label validi (0, 1, 2), aggiorniamo la colonna e controlliamo che sia tutto corretto:"""

df_train = df_train[df_train["label"].isin([0, 1, 2])]

df_train["label_text"] = df_train["label"].map(label_map)

df_train["label"].unique(),
df_train["label_text"].isnull().sum()

"""ANALISI DATI:

Contiamo le classi e rappresentiamo la loro distribuzione per vedere se sia bilanciata:
"""

print(df_train["label_text"].value_counts())

sns.countplot(x="label_text", data=df_train)
plt.title("Distribuzione delle classi nel training set")
plt.xlabel("Classe")
plt.ylabel("Numero di esempi")
plt.show()

"""Le classi risultano ben bilanciate

Adesso vogliamo capire:
* quante parole in media hanno le
premesse (sentenze di partenza) e le ipotesi (sentenze da valutare)

* se sono presenti frasi molto corte o molto lunghe

* se sono presenti frasi complesse o semplici.


Per fare ciò aggiungo due colonne:

premise_len = numero di parole nella premessa

hypotesis_len = numero di parole nell'ipotesi
"""

df_train["premise_len"] = df_train["premise"].apply(lambda x:
len(str(x).split()))
df_train["hypothesis_len"] = df_train["hypothesis"].apply(lambda x: len(str(x).split()))
# Mostra le prime righe per confermare
df_train[["premise", "premise_len", "hypothesis",
"hypothesis_len"]].head()

df_train[["premise_len", "hypothesis_len"]].describe()

"""Risulta che le premesse sono in media più lunghe delle ipotesi; che alcune frasi arrivano a 70+ parole e, infine, la distribuzione è abbastanza normale"""

plt.figure(figsize=(10, 4))
sns.histplot(df_train["premise_len"], bins=30, kde=True)
plt.title("Distribuzione lunghezza delle 'premise'")
plt.xlabel("Numero di parole")
plt.ylabel("Frequenza")
plt.show()

plt.figure(figsize=(10, 4))
sns.histplot(df_train["hypothesis_len"], bins=30, kde=True,
color='orange')
plt.title("Distribuzione lunghezza delle 'hypothesis'")
plt.xlabel("Numero di parole")
plt.ylabel("Frequenza")
plt.show()

plt.figure(figsize=(8, 5))
sns.boxplot(data=df_train[["premise_len", "hypothesis_len"]])
plt.title("Boxplot lunghezze: Premise vs Hypothesis")
plt.ylabel("Numero di parole")
plt.show()

"""Adesso ci addentriamo nella preparazione dei dati finalizzata alla costruzione del modello di machine learning.

Approccio base: TF-IDF (vettorizzazione classica) + Logistic regression
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

#questo ci servirà dopo
!pip install transformers --quiet
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification, Trainer, TrainingArguments
from datasets import Dataset
import torch

"""PREPROCESSING TESUALE: creiamo un'unica colonna text che unisca 'premise' e 'hypotesis'"""

# Unione delle due frasi in un’unica colonna di input
df_train["text"] = df_train["premise"] + " [SEP] " + df_train["hypothesis"]

# Controllo visivo delle prime righe
df_train[["text", "label_text"]].head()

"""Iniziamo il processo di vettorizzazione con TF-IDF: vogliamo trasformare un testo unico in vettori numerici, per pesare le parole in base alla loro importanza."""

# Inizializziamo il vettorizzatore TF-IDF
vectorizer = TfidfVectorizer(max_features=10000, ngram_range=(1, 2))

# Trasformiamo il testo in vettori numerici
X = vectorizer.fit_transform(df_train["text"])
y = df_train["label"]

X.shape #dimensione della matrice TF-IDF

"""Suddividiamo i dati in Train set e Validation set: 80% training, 20% validation"""

X_train, X_val, y_train, y_val = train_test_split( X, y, test_size=0.2, random_state=42, stratify=y
)

X_train.shape, X_val.shape  #controlliamo le dimensioni dei set

"""ADDESTRAMENTO DEL MODELLO LOGISTIC REGRESSION:"""

# Inizializziamo il modello
model = LogisticRegression(max_iter=1000, solver='saga', n_jobs=-1)

#Addestriamo il modello
model.fit(X_train, y_train)

"""VALUTAZIONE DEL MODELLO:"""

# Predizioni sul validation set
y_pred = model.predict(X_val)

print("Classification Report:")
print(classification_report(y_val, y_pred, target_names=["entailment", "neutral", "contradiction"]))

print("Confusion Matrix:")
print(confusion_matrix(y_val, y_pred))

"""MIGLIORAMENTI MODELLO:"""

TfidfVectorizer(max_features=30000, ngram_range=(1,3))  #aumentiamo le feature del TF-IDF

import re
df_train["text_clean"] = df_train["text"].apply(lambda x: re.sub(r"[^\w\s]", "", x.lower()))   #puliamo il testo

vectorizer = TfidfVectorizer(max_features=30000, ngram_range=(1, 3))

"""Dopo aver modificato la rappresentazione TF-IDF ripetiamo l'addestramento:"""

X = vectorizer.fit_transform(df_train["text"])

X_train, X_val, y_train, y_val = train_test_split( X, y, test_size=0.2, random_state=42, stratify=y)
X_train.shape, X_val.shape

model = LogisticRegression(max_iter=1000, solver='saga', n_jobs=-1)

model.fit(X_train, y_train)

y_pred = model.predict(X_val)
print("Classification Report:")
print(classification_report(y_val, y_pred, target_names=["entailment", "neutral", "contradiction"]))

print("Confusion Matrix:")
print(confusion_matrix(y_val, y_pred))

model = LogisticRegression(max_iter=1000, solver='saga', n_jobs=-1, class_weight='balanced')

model.fit(X_train, y_train)

y_pred = model.predict(X_val)
print("Classification Report:")
print(classification_report(y_val, y_pred, target_names=["entailment", "neutral", "contradiction"]))

"""MODELLO RETE NEURALE (AVANZATO)

Importiamo le librerie fondamentali per il modello neurale e per la valutazione; per migliorarne la velocità abbiamo impostato il devide su "cuda" o "cpu":
"""

!pip install pytorch_lightning --quiet

# Librerie principali per deep learning e modellazione
import torch
import torch.nn as nn
import torch.nn.functional as F
import pytorch_lightning as pl

from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix

device = torch.device("cuda" if torch.cuda.is_available()
else "cpu")
print(f"using device: {device}")

"""TOKENIZZAZIONE DELLE FRASI:

Creiamo una funzione preprocess() che trasforma una frase in una lista di parole.
"""

# Funzione di preprocessing e tokenizzazione
def preprocess(sentence):
 # Conversione in minuscolo e split su spazi
 return sentence.lower().split()

example = "A person on a horse jumps over a broken down airplane."
print(preprocess(example))

"""Per migliorare la fase di tokenizzazione, aggiungiamo anche la rimozione della punteggiatura:"""

import string
def tokenize(text):
 text = text.lower() # minuscole
 tokens = text.split() # tokenizzazione base
 tokens = [token.strip(string.punctuation) for token in tokens] # rimuove .,!? etc.
 return tokens

example = df_train["premise"].iloc[0]
print(tokenize(example))

"""Creiamo un dizionario:
* Tokenizzaimo tutte le frasi;
* uniamo tutti i tokens (con barra) per avere un'unica lista;
* contiamo quante volte compare ogni parola;
* creiamo il dizionario, applicando ad ogni parola un indice numerico;
* aggiungiamo i token speciali <PAD> (per allineare le frasi ad una lughezza fissa) e <UNK> (per gestire le parole sconosciute)
"""

!pip install tqdm --quiet
from tqdm.notebook import tqdm
from collections import Counter
# Tokenizzazione con barra di avanzamento
tqdm.pandas(desc="Tokenizing")

df_train["premise_tokens"] = df_train["premise"].progress_apply(tokenize)
df_train["hypothesis_tokens"] = df_train["hypothesis"].progress_apply(tokenize)

# Unione dei token (premise + hypothesis) con barra
all_tokens = []
for prem, hypo in tqdm(zip(df_train["premise_tokens"], df_train["hypothesis_tokens"]), total=len(df_train), desc="Merging tokens"):
  all_tokens.extend(prem)
  all_tokens.extend(hypo)

# Conta le frequenze dei token
token_freq = Counter(all_tokens)
# Costruzione del vocabolario con token speciali
vocab = {"<PAD>": 0, "<UNK>": 1}
for token in tqdm(token_freq, desc="Building vocab"):
  vocab[token] = len(vocab)

# Visualizza i primi elementi
list(vocab.items())[:10]

"""ENCODING FRASI:

Convertiamo ogni frase in una lista di indici numerici, assegnando un numero a ciascun token e creando sequenze di lunghezza dissa tramite padding e truncation.
"""

# Funzione per effettuare il padding delle frasi
def encode_sentence(sentence, vocab, max_length=20):
 tokens = [vocab.get(token, vocab["<UNK>"]) for token in sentence]
 # Esegui il padding o truncation a lunghezza fissa
 if len(tokens) < max_length:
  tokens += [vocab["<PAD>"]] * (max_length - len(tokens)) # Padding
 else:
  tokens = tokens[:max_length] # Truncation

# Applichiamo il padding/truncation su tutte le frasi
df_train["encoded_premise"] = df_train["premise_tokens"].apply(lambda x: encode_sentence(x, vocab))
df_train["encoded_hypothesis"] = df_train["hypothesis_tokens"].apply(lambda x: encode_sentence(x, vocab))

df_train[["encoded_premise", "encoded_hypothesis"]].head()

"""CREAZIONE DATASET PYTORCH:"""

from torch.utils.data import Dataset

# Classe custom Dataset per SNLI
class SNLIDataset(Dataset):
  def __init__(self, premises, hypotheses, labels, vocab, max_len=50):
    self.premises = premises
    self.hypotheses = hypotheses
    self.labels = labels
    self.vocab = vocab
    self.max_len = max_len

  def __len__(self):
    return len(self.labels)

  def encode_sentence(self, tokens):
    encoded = [self.vocab.get(tok, self.vocab["<UNK>"]) for tok in tokens]
    if len(encoded) < self.max_len:
      encoded += [self.vocab["<PAD>"]] * (self.max_len - len(encoded))
    else:
      encoded = encoded[:self.max_len]
    return encoded

  def __getitem__(self, idx):
    prem_tokens = self.premises[idx]
    hypo_tokens = self.hypotheses[idx]

    label = self.labels[idx]

    prem_encoded = self.encode_sentence(prem_tokens)
    hypo_encoded = self.encode_sentence(hypo_tokens)

    return {
        "premise": torch.tensor(prem_encoded),
        "hypothesis": torch.tensor(hypo_encoded),
        "label": torch.tensor(label)
        }

"""CREAZIONE DEL DATALOADER"""

from torch.utils.data import DataLoader
from sklearn.model_selection import train_test_split
# Parametri
BATCH_SIZE = 64

# Suddivisione 80% train, 20% validation (con stratificazione)
train_df, val_df = train_test_split(df_train, test_size=0.2, random_state=42, stratify=df_train["label"])

#Dataset PyTorch corretti
train_dataset = SNLIDataset(
 premises = train_df["premise_tokens"].tolist(),
 hypotheses = train_df["hypothesis_tokens"].tolist(),
 labels = train_df["label"].tolist(),
 vocab = vocab
)
val_dataset = SNLIDataset(
 premises = val_df["premise_tokens"].tolist(),
 hypotheses = val_df["hypothesis_tokens"].tolist(),
 labels = val_df["label"].tolist(),
 vocab = vocab
)
# DataLoader PyTorch
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE)

"""MODELLO SENTENCE CLASSIFIER:"""

import torch.nn as nn

class SentenceClassifier(nn.Module):
 def __init__(self, vocab_size, embed_dim=100, hidden_dim=128, output_dim=3):
  super().__init__()
  self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
  self.lstm = nn.LSTM(embed_dim, hidden_dim, batch_first=True, bidirectional=True)
  self.fc = nn.Linear(hidden_dim * 4, output_dim) # 2 * hidden x 2 sequence (prem + hypo)

 def forward(self, premise, hypothesis):
   # Embedding
    prem_emb = self.embedding(premise)
    hypo_emb = self.embedding(hypothesis)
  # LSTM
    _, (prem_hidden, _) = self.lstm(prem_emb)
    _, (hypo_hidden, _) = self.lstm(hypo_emb)
 # Concateniamo i due output (fw + bw) da premessa e ipotesi
    prem_rep = torch.cat([prem_hidden[0], prem_hidden[1]], dim=1)
    hypo_rep = torch.cat([hypo_hidden[0], hypo_hidden[1]], dim=1)
# Concatenazione finale + classificazione
    combined = torch.cat([prem_rep, hypo_rep], dim=1)
    output = self.fc(combined)

    return output

"""SNLI CLASSIFIER LIGHTNING: LIGHTNINGMODULE per training e validazione"""

import pytorch_lightning as pl
import torch.nn.functional as F
from tqdm import tqdm

class SNLIClassifierLightning(pl.LightningModule):
  def __init__(self, model, lr=1e-3):
    super().__init__()
    self.save_hyperparameters() #Traccia i parametri
    self.model = model
    self.lr = lr

  def forward(self, premise, hypothesis):
    return self.model(premise, hypothesis)

  def training_step(self, batch, batch_idx):
    logits = self.forward(batch["premise"], batch["hypothesis"])
    loss = F.cross_entropy(logits, batch["label"])
    preds = torch.argmax(logits, dim=1)
    acc = (preds == batch["label"]).float().mean()
    self.log("train_loss", loss, prog_bar=True)
    self.log("train_acc", acc, prog_bar=True)
    return loss

  def validation_step(self, batch, batch_idx):
    logits = self.forward(batch["premise"], batch["hypothesis"])
    loss = F.cross_entropy(logits, batch["label"])
    preds = torch.argmax(logits, dim=1)
    acc = (preds == batch["label"]).float().mean()
    self.log("val_loss", loss, prog_bar=True)
    self.log("val_acc", acc, prog_bar=True)

  def configure_optimizers(self):
    return torch.optim.Adam(self.parameters(), lr=self.lr)

"""ADDESTRAMENTO:"""

import pytorch_lightning as pl
import torch
import torch.nn as nn

class SNLIModel(pl.LightningModule):
  def __init__(self, vocab_size, embedding_dim=100, hidden_dim=128, num_classes=3, lr=1e-3):
    super().__init__()
    self.save_hyperparameters()
    self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)
    self.lstm = nn.LSTM(embedding_dim, hidden_dim, batch_first=True, bidirectional=True)
    self.classifier = nn.Linear(hidden_dim * 4, num_classes)
    self.loss_fn = nn.CrossEntropyLoss()
    self.lr = lr

  def forward(self, premise, hypothesis):
    prem_emb = self.embedding(premise)
    hypo_emb = self.embedding(hypothesis)
    _, (prem_hn, _) = self.lstm(prem_emb)
    _, (hypo_hn, _) = self.lstm(hypo_emb)

    prem_repr = torch.cat((prem_hn[0], prem_hn[1]), dim=-1)
    hypo_repr = torch.cat((hypo_hn[0], hypo_hn[1]), dim=-1)
    combined = torch.cat([prem_repr, hypo_repr], dim=-1)
    return self.classifier(combined)

  def training_step(self, batch, batch_idx):
    logits = self.forward(batch["premise"], batch["hypothesis"])
    loss = self.loss_fn(logits, batch["label"])
    self.log("train_loss", loss, prog_bar=True)
    return loss

  def validation_step(self, batch, batch_idx):
    logits = self.forward(batch["premise"], batch["hypothesis"])
    loss = self.loss_fn(logits, batch["label"])
    preds = torch.argmax(logits, dim=1)
    acc = (preds == batch["label"]).float().mean()
    self.log("val_loss", loss, prog_bar=True)
    self.log("val_acc", acc, prog_bar=True)

  def configure_optimizers(self):
    return torch.optim.Adam(self.parameters(), lr=self.lr)

!pip install pytorch_lightning --quiet

"""INIZIALIZZAZIONE MODELLO E AVVIO DEL TRAINING:"""

from pytorch_lightning import Trainer

# Inizializza il modello con dimensione del vocabolario
model_lightning = SNLIModel(vocab_size=len(vocab))
# Trainer con barra di avanzamento
trainer = Trainer(max_epochs=5, accelerator="auto")
# Avvia il training (barra inclusa)
trainer.fit(model_lightning, train_loader, val_loader)

"""VALUTAZIONE DEL MODELLO"""

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm # Importa tqdm per la barra

# Funzione per ottenere tutte le predizioni sul validation set (con barra)
def evaluate_model(model, dataloader):
  model.eval()
  all_preds = []
  all_labels = []

  with torch.no_grad():
      for batch in tqdm(dataloader, desc="Valutazione in corso"):
        premise = batch["premise"].to(device)
        hypothesis = batch["hypothesis"].to(device)
        labels = batch["label"].to(device)
        outputs = model(premise, hypothesis)
        preds = torch.argmax(outputs, dim=1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

  return all_labels, all_preds

# Ottieni predizioni
y_true, y_pred = evaluate_model(model_lightning, val_loader)

# Classification report
print("Classification Report:\n")
print(classification_report(y_true, y_pred,
target_names=["entailment", "neutral", "contradiction"]))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",xticklabels=["entailment", "neutral", "contradiction"], yticklabels=["entailment", "neutral", "contradiction"])
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.show()

"""TRAINING FINALE CON EARLYSTOPPING"""

from pytorch_lightning import Trainer
from pytorch_lightning.callbacks import EarlyStopping
# Callback EarlyStopping
early_stop_callback = EarlyStopping(monitor="val_loss",patience=5,mode="min",verbose=True)

# Inizializza il modello
model_lightning = SNLIModel(vocab_size=len(vocab))
# Trainer con early stopping e barra di avanzamento
trainer = Trainer(
 max_epochs=20,
 accelerator="auto",
 callbacks=[early_stop_callback]
)
# Avvia il training
trainer.fit(model_lightning, train_loader, val_loader)